services:
  app:
    image: golang:1.19.5-alpine
    ports:
      - "1323:1323"
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/kosukeohmura/go-web-server-sample
    working_dir: /go/src/github.com/kosukeohmura/go-web-server-sample
    command: go run main.go
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.31
    platform: linux
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: debug
      MYSQL_DATABASE: go_web_server_sample_debug
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --default-storage-engine=innodb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
  operator:
    build:
      context: .
      dockerfile: DockerfileOperator
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/kosukeohmura/go-web-server-sample
    working_dir: /go/src/github.com/kosukeohmura/go-web-server-sample
    tty: true
