services:
  rdb:
    image: mysql:8.0.31
    platform: linux
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: debug
      MYSQL_DATABASE: go_web_server_sample_debug
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --default-storage-engine=innodb
  operator:
    build:
      context: .
      dockerfile: DockerfileOperator
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/kosukeohmura/go-web-server-sample
    working_dir: /go/src/github.com/kosukeohmura/go-web-server-sample
    tty: true
